### ISSUE TITLE
Close svg cannot load, broken link

### ISSUE THREAD

**Issue by casKd-dev** [CapnKitten/BetterDiscord#5]
### Problem:
So the theme tries to reach `https://capnkitten.github.io/assets/7731c77d99babca1a8faec204d98c380.svg` for the X svg on the `notice-3I4-y_` when the DevilBro theme/repo plugin warns about outdated plugins, but this is what i get:
![](https://s5.postimg.cc/oi1rqclx3/screenshot_237.png)
### Exact Element that creates the problem:
`dismiss-1QjyJW`
### Notes:
It is not a z-index problem, as i've tried to fix it myself.
### Possible fix:
Change `background: url()` of `dismiss-1QjyJW` to updated svg.

**Comment by CapnKitten** [comment]
Sorry about that, forgot to add the discord url to it. It's fixed in the latest update.
