### ISSUE TITLE
Suggestion: Lower z-index of .backdrop-1ocfXc

### ISSUE THREAD

**Issue by casKd-dev** [CapnKitten/BetterDiscord#7]
The `z-index` doesn't need to be this high, i recommend lowering it as it covers some modals. My value for fixing most problems is the following:
```
.backdrop-1ocfXc {
    z-index: 120 !important;
}
```

_Thanks for making this theme, and keep doing good work!_

**Comment by CapnKitten** [comment]
Will do, thanks. It'll be in the next update.
