### ISSUE TITLE
Dialogue box style is not working

### ISSUE THREAD

**Issue by imTheSupremeOne** [CapnKitten/BetterDiscord#9]
After last update dialogue boxes style disappeared... I've checked your changelog and there is no words about that. Disabling all plugins didn't help. Don't run multiple theme, don't even know is that possible:

Screen:
![image](https://user-images.githubusercontent.com/13508453/43183994-badf4f70-8fef-11e8-8bfa-986168114036.png)

Prev. it looked like on your screens:
![image](https://user-images.githubusercontent.com/13508453/43184170-528c0822-8ff0-11e8-93cc-8f7933e942dc.png)

**Comment by CapnKitten** [comment]
The recent Discord update broke a lot of the main chat stuff. It'll be fixed with the next update. I'm almost done with it.
